version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        command: "npm run dev"
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
        env_file:
            .env
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        depends_on:
            - redis
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
